'use-client'
import Head from 'next/head'

import styles from '@/styles/Home.module.css'
import Header from '@/Components/Header'
import { useState } from 'react'
import Todos from '@/Components/Todos'
import { useContext } from 'react';
import { Context } from '../Context/ContextApi';



export default function Home() {
  const {toggle } = useContext(Context)
  return (
    <>
      <Head>
        <title>TodoApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <main >
        <Header />
        <main className={[toggle===true ?  styles.modelbgblur : ''].join(" ")}  >
          <Todos />
        </main>

      </main>
    </>
  )
}
